# FTP服务器配置文件示例
# 复制此文件为ftp_config.yaml并修改为实际配置

# 源FTP服务器信息
source:
  host: "192.168.1.13" # 主机
  port: 2123  # FTP端口，默认21
  user: "NasSrv" # 用户名
  password: "1" # 密码
  directory: "/demo" # 目录
  enable_backup: false # 是否启用备份
  backup_directory: /backup # 备份目录
  encoding: "gb2312" # 编码

  file_filter:
    type: "modification_time" # 文件过滤类型，可选值：all(全部文件), pattern(按字符匹配), extension(按后缀匹配), creation_time(按创建时间), modification_time(按修改时间)
    time_value: # 配置一个，表示 file_time < 第一个时间，配置两个: file_time < 第一个时间 and file_time >= 第二个时间 
      # 时间值，格式：YYYY-MM-DD HH:MM:SS, 或者 current_day, current_hour, current_minute, current_time, days_before_{n}, hours_before_{n}, minutes_before_{n}
      # 假设当前时间为 2025-09-11 12:15:31.383282
      #  current_day -- 当天: 例如 2025-09-11 00:00:00, 
      #  current_hour -- 当前小时: 例如 2025-09-11 12:00:00,
      #  current_minute -- 当前分钟: 例如 2025-09-11 12:15:00, 
      #  current_time -- 当前时间: 例如 2025-09-11 12:15:31, 
      #  days_before_{n} -- 前n天: 例如 days_before_1 -- 前1天: 2025-09-10 00:00:00, days_before_2 -- 前2天: 2025-09-09 00:00:00, 
      #  hours_before_{n} -- 前n小时: 例如 hours_before_1 -- 前1小时: 2025-09-11 11:00:00, hours_before_2 -- 前2小时: 2025-09-11 10:00:00, 
      #  minutes_before_{n} -- 前n分钟: 例如 minutes_before_1 -- 前1分钟: 2025-09-11 12:14:00, minutes_before_2 -- 前2分钟: 2025-09-11 12:13:00
      - "current_hour"
      - "hours_before_5"

# 目标FTP服务器信息
destination:
  host: "192.168.1.25" # 主机
  port: 2121  # FTP端口，默认21
  user: "demo" # 用户名
  password: "1" # 密码
  directory: "/dest" # 目录
  encoding: "utf-8" # 编码
  file_exists_strategy: "skip" # 文件存在策略，可选值：overwrite(覆盖), skip(跳过), rename(重命名)

# 日志配置
log:
  file: "./data/log/ftp_transfer.log"  # 日志文件路径
  rotation: "1 week"        # 日志轮转策略
  retention: "1 month"      # 日志保留时间
  level: "DEBUG"             # 日志级别

# 邮件通知配置
email:
  enable: true                      # 是否启用邮件通知
  subject: "FTP文件传输任务报告"     # 邮件主题
  sender: "emrys.liu@foxmail.com"  # 发送者邮箱
  recipients:                       # 接收者邮箱列表
    - "emrys.liu@foxmail.com"
    # - "recipient2@example.com"
  smtp_server: "smtp.qq.com"   # SMTP服务器地址
  smtp_port: 465                    # SMTP服务器端口
  smtp_username: "emrys.liu@foxmail.com"  # SMTP用户名
  smtp_password: "ncyuytguwiiibefi"    # SMTP密码或授权码
  failure_threshold: 3              # 失败文件数量阈值，超过此值发送警告邮件
